config/routes.rb
Fitnesstask::Application.routes.draw do
  resources :groupsetitems

  resources :groupsets

  resources :exercises

  resources :trainings

  resources :workouts

end

app/models/training.rb
class Training < ActiveRecord::Base
  belongs_to :workout
  has_many :groupsets
  has_many :exercises, :through => :groupsets
  accepts_nested_attributes_for :groupsets

  # Helpermethod for displaying a hole training with sets and exercisese
  def find_groupset(id)
  	Groupset.where(:training_id => (id))
  end


  # For automcomplete and prevent simple duplication
  def workout_name
    workout.try(:name)
  end
  
  def workout_name=(name)
    self.workout = Workout.where(:name => name).first_or_create
  end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    @training_groupset = Groupset.where(:training_id => params[:id])
    @training_exercise = Exercise.where(:id => @training_groupset)
    @training_groupset_item = Groupsetitem.where(:groupset_id => @training_groupset)
  end

  # GET /trainings/new
  def new
    if params[:id].present?
      @training = Training.new(:workout_id => params[:id])
      @exercise_array = Workoutexercise.where(:workout_id => params[:id]).map(&:exercise_id)
      for i in 0..(@exercise_array.count-1)
        @training.groupsets.build(:exercise_id => @exercise_array[i])
      end
    else
      @training = Training.new      
    end
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save

        @training.workout.exercises << @training.exercises
        @training.workout.save

        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render action: 'show', status: :created, location: @training }
      else
        format.html { render action: 'new' }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit!
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<div class="container-wo cf">
  <section class="main">
    <%= nested_form_for(@training) do |f| %>
      <% if @training.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>

          <ul>
          <% @training.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :workout_name %><br>
        <%= f.text_field :workout_name, data: {autocomplete_source: Workout.order(:name).map(&:name)}, :class => 'autocomplete_workout'  %>
      </div>
      <h1>Groupset</h1>
      <%= f.fields_for :groupsets do |builder| %>
        <%= render 'groupset_fields', f: builder %>
      <% end %>
      <p><%= f.link_to_add "Add Groupset", :groupsets, :class => 'btn green' %></p>
  </section>
  <aside>
    <div class="actions">
      <button id="submit-form-button" class="btn">Save Training</button>
    </div>  
    <div class="field">
      <%= f.label :notes %><br>
      <%= f.text_area :notes %>
    </div>
    <div class="field">
      <%= f.label :starttime %><br>
      <%= f.datetime_select :starttime %>
    </div>
    <div class="field">
      <%= f.label :endtime %><br>
      <%= f.datetime_select :endtime %>
    </div>
  </aside>
  
<% end %>


</div>

app/views/trainings/_groupset_fields.html.erb
<fieldset class="first">
  <div class="field">
    <%= f.label :exercise_name, "Exercise Name" %><br>
    <%= f.text_field :exercise_name, data: {autocomplete_source: Exercise.order(:name).map(&:name)}, :class => 'autocomplete_exercise' %>
  </div>
  <%= f.fields_for :groupsetitems do |builder| %>
    <%= render 'groupsetitem_fields', f: builder %>
  <% end %>

  <p><%= f.link_to_add "Add a Set", :groupsetitems, :class => 'btn green' %></p>

  <%= f.link_to_remove "Remove this Groupset" %>
</fieldset>

app/views/trainings/_groupsetitem_fields.html.erb
<fieldset class="second cf">
  <div class="field col-30">
    <%= f.label :repetition, :class => 'col-40' %>
    <%= f.number_field :repetition, :class => 'col-20' %>
  </div>
  <div class="field col-30">
    <%= f.label :kgweight, :class => 'col-40' %>
    <%= f.text_field :kgweight, :class => 'col-20' %>
  </div>
  <div class="field col-30">
    <%= f.label :lbweight, :class => 'col-40' %>
    <%= f.text_field :lbweight, :class => 'col-20' %>
  </div>
  <%= f.link_to_remove "Remove", :class => 'col-10' %>
</fieldset>

app/views/trainings/edit.html.erb
<h1>Editing training</h1>

<%= render 'form' %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<h1>Listing trainings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Notes</th>
      <th>Starttime</th>
      <th>Endtime</th>
      <th>Workout</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training.name %></td>
        <td><%= training.notes %></td>
        <td><%= training.starttime %></td>
        <td><%= training.endtime %></td>
        <td><%= training.workout.name %></td>
        <td><%= link_to 'Show', training %></td>
        <td><%= link_to 'Edit', edit_training_path(training) %></td>
        <td><%= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Training', new_training_path, :class => 'btn' %>

app/views/trainings/new.html.erb
<h1>New training</h1>

<%= render 'form' %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @training.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @training.notes %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @training.starttime %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @training.endtime %>
</p>

<p>
  <strong>Workout:</strong>
  <%= @training.workout.name %>
</p>

<% @training.find_groupset(@training.id).each do |groupset| %>

  <h3><%= groupset.exercise.name %></h3>

  <% groupset.find_groupsetitems(groupset).each do |groupsetitem| %>
    <p>
      <strong><%= groupsetitem.repetition %></strong>  
      <%= groupsetitem.kgweight %>kg
      <%= groupsetitem.lbweight %>lb
    </p>
  <% end %> 

<% end %>




<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>