config/routes.rb
Fitnesstask::Application.routes.draw do
  resources :groupsetitems

  resources :groupsets

  resources :exercises

  resources :trainings

  resources :workouts

end

app/models/workout.rb
class Workout < ActiveRecord::Base
	has_many :trainings
	has_many :workoutexercises
  has_many :exercises, through: :workoutexercises
  attr_reader :exercise_tokens
  
  def exercise_tokens=(ids)
    self.exercise_ids = ids.split(",")
  end
  
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
    # Thats probably no the best way haha
    # right!
    #@workout_exercises = Workoutexercise.where(:workout_id => params[:id])
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render action: 'show', status: :created, location: @workout }
      else
        format.html { render action: 'new' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit! #(:name, exercises_attributes: [:name, :notes])
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :exercise_ids, "Exercises" %><br/>
    <%= f.collection_select :exercise_ids, Exercise.order(:name), :id, :name, {}, {multiple:true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<h1>All Workouts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout.name %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path, :class => 'btn' %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @workout.name %></h1>
<h3>Exercises</h3>
<% if @workout.exercises.any? %>
	<ul>
	<% @workout.exercises.each do |exercise| %>
	<li><%= exercise.name %></li>
	<% end %>
	</ul>
<% else %>
	<p>Sorry, no exercises yet...</p>
<% end %>
<hr>

<h3>Trainings</h3>
<% if @workout.trainings.any? %>
	<ul>
	<% @workout.trainings.each do |training| %>
	<li><%= training.name %></li>
	<% end %>
	</ul>
<% else %>
	<p>Sorry, no trainings yet...</p>
<% end %>
<hr>
<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>