config/routes.rb
Fitnesstask::Application.routes.draw do
  resources :groupsetitems

  resources :groupsets

  resources :exercises

  resources :trainings

  resources :workouts

end

app/models/groupsetitem.rb
class Groupsetitem < ActiveRecord::Base
  belongs_to :groupset
end

app/controllers/groupsetitems_controller.rb
class GroupsetitemsController < ApplicationController
  before_action :set_groupsetitem, only: [:show, :edit, :update, :destroy]

  # GET /groupsetitems
  # GET /groupsetitems.json
  def index
    @groupsetitems = Groupsetitem.all
  end

  # GET /groupsetitems/1
  # GET /groupsetitems/1.json
  def show
  end

  # GET /groupsetitems/new
  def new
    @groupsetitem = Groupsetitem.new
  end

  # GET /groupsetitems/1/edit
  def edit
  end

  # POST /groupsetitems
  # POST /groupsetitems.json
  def create
    @groupsetitem = Groupsetitem.new(groupsetitem_params)

    respond_to do |format|
      if @groupsetitem.save
        format.html { redirect_to @groupsetitem, notice: 'Groupsetitem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @groupsetitem }
      else
        format.html { render action: 'new' }
        format.json { render json: @groupsetitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groupsetitems/1
  # PATCH/PUT /groupsetitems/1.json
  def update
    respond_to do |format|
      if @groupsetitem.update(groupsetitem_params)
        format.html { redirect_to @groupsetitem, notice: 'Groupsetitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @groupsetitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groupsetitems/1
  # DELETE /groupsetitems/1.json
  def destroy
    @groupsetitem.destroy
    respond_to do |format|
      format.html { redirect_to groupsetitems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_groupsetitem
      @groupsetitem = Groupsetitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def groupsetitem_params
      params.require(:groupsetitem).permit(:repetition, :kgweight, :lbweight, :groupset_id)
    end
end

app/helpers/groupsetitems_helper.rb
module GroupsetitemsHelper
end

app/views/groupsetitems/_form.html.erb
<%= form_for(@groupsetitem) do |f| %>
  <% if @groupsetitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@groupsetitem.errors.count, "error") %> prohibited this groupsetitem from being saved:</h2>

      <ul>
      <% @groupsetitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :repetition %><br>
    <%= f.number_field :repetition %>
  </div>
  <div class="field">
    <%= f.label :kgweight %><br>
    <%= f.text_field :kgweight %>
  </div>
  <div class="field">
    <%= f.label :lbweight %><br>
    <%= f.text_field :lbweight %>
  </div>
  <div class="field">
    <%= f.label :groupset_id %><br>
    <%= f.text_field :groupset_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groupsetitems/edit.html.erb
<h1>Editing groupsetitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @groupsetitem %> |
<%= link_to 'Back', groupsetitems_path %>

app/views/groupsetitems/index.html.erb
<h1>Listing groupsetitems</h1>

<table>
  <thead>
    <tr>
      <th>Repetition</th>
      <th>Kgweight</th>
      <th>Lbweight</th>
      <th>Groupset</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groupsetitems.each do |groupsetitem| %>
      <tr>
        <td><%= groupsetitem.repetition %></td>
        <td><%= groupsetitem.kgweight %></td>
        <td><%= groupsetitem.lbweight %></td>
        <td><%= groupsetitem.groupset %></td>
        <td><%= link_to 'Show', groupsetitem %></td>
        <td><%= link_to 'Edit', edit_groupsetitem_path(groupsetitem) %></td>
        <td><%= link_to 'Destroy', groupsetitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Groupsetitem', new_groupsetitem_path %>

app/views/groupsetitems/new.html.erb
<h1>New groupsetitem</h1>

<%= render 'form' %>

<%= link_to 'Back', groupsetitems_path %>

app/views/groupsetitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Repetition:</strong>
  <%= @groupsetitem.repetition %>
</p>

<p>
  <strong>Kgweight:</strong>
  <%= @groupsetitem.kgweight %>
</p>

<p>
  <strong>Lbweight:</strong>
  <%= @groupsetitem.lbweight %>
</p>

<p>
  <strong>Groupset:</strong>
  <%= @groupsetitem.groupset %>
</p>

<%= link_to 'Edit', edit_groupsetitem_path(@groupsetitem) %> |
<%= link_to 'Back', groupsetitems_path %>