config/routes.rb
Fitnesstask::Application.routes.draw do
  resources :groupsetitems

  resources :groupsets

  resources :exercises

  resources :trainings

  resources :workouts

end

app/views/layouts/_navigation.html.erb
<header class="header cf">
	<a class="logo">
		<h1>fitnesstask</h1>
	</a>
	<div class="right">
		<div class="link profile">
			<a href="#">jurekbarth</a>
			<ul class="profile">
				<li><a href="#"><span class="fa fa-refresh"></span>Change Profilepicture</a></li>
				<li><a href="#"><span class="fa fa-cog"></span>Settings</a></li>
				<!-- <li><a href="#"><span class="fa fa-sign-out"></span>Logout</a></li> -->
			</ul>
		</div>
		<a class="link" href="#"><span class="fa fa-sign-out"></span>Logout</a>
	</div>
</header>

<nav class="main-nav">
	<ul>
		<li><a class="" href="#"><span class="fa fa-tachometer"></span>Dashboard</a></li>
		<li><a class="active" href="#"><span class="fa fa-archive"></span>Data</a>
			<ul>
				<li><%= link_to 'Workouts', workouts_path %></li>
				<li><%= link_to 'Excercises', exercises_path %></li>
				<li><%= link_to 'Trainings', trainings_path %></li>
				<!-- <li><%= link_to 'Groupsets', groupsets_path %></li>
				<li><%= link_to 'Sets', groupsetitems_path %></li> -->
			</ul>
		</li>
		<li><a href="#"><span class="fa fa-tasks"></span>Analytics</a></li>
		<li><a href="#"><span class="fa fa-calendar"></span>Training Plan</a></li>
		<li><a href="#"><span class="fa fa-shopping-cart"></span>Store</a></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fitnesstask</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render '/layouts/navigation' %>
<div class="main-content cf">
	<%= yield %>
</div>
</body>
</html>